### ISSUE TITLE
ECOM-1: Need to fix the functionality of quantity addition/removal of cart items page 

### ISSUE THREAD

**Issue by sauramandal** [Montai/NodeAppPrototype#2]
Currently upon change of quantity of products price is not getting calculated properly for each product.
Also the final total price after each trigger of add/remove buttons should be updated dynamically.
![Capture1](https://user-images.githubusercontent.com/8455623/55994877-9688a000-5cd0-11e9-8a4e-3ee3d85c6c76.PNG)
![Capture2](https://user-images.githubusercontent.com/8455623/55994880-9688a000-5cd0-11e9-8516-579b618fd25d.PNG)

**Comment by prisar** [comment]
In both two places, it should be changed, like in subtotal and Total.

**Comment by prisar** [comment]
/products/showCartItems page is not opening
